name: Publish from Git Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-from-tag:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Extract version from tag
      id: extract_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Publishing version: $VERSION"
        
    - name: Update version in gradle.properties
      run: |
        sed -i "s/library.version=.*/library.version=${{ steps.extract_version.outputs.version }}/" gradle.properties
        
    - name: Build and publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPR_KEY: ${{ secrets.GITHUB_TOKEN }}
        GPR_USER: ${{ github.repository_owner }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        # Set up credentials for GitHub Packages
        echo "gpr.user=${{ github.repository_owner }}" >> gradle.properties
        echo "gpr.key=${{ secrets.GITHUB_TOKEN }}" >> gradle.properties
        echo "github.owner=${{ github.repository_owner }}" >> gradle.properties
        echo "github.repo=${{ github.repository }}" >> gradle.properties
        ./gradlew clean build publish
        
    - name: Show published artifact info
      run: |
        echo "✅ Successfully published version ${{ steps.extract_version.outputs.version }}"
        echo "📦 Package: com.lastbenchcap.common.gradle:com.lastbenchcap.common.gradle:${{ steps.extract_version.outputs.version }}"
        echo "🔗 Repository: https://maven.pkg.github.com/${{ github.repository }}" 